### ISSUE TITLE
uninitialized constant ActiveSupport::ParameterFilter in version 1.8.3 with rails 6

### ISSUE THREAD

**Issue by SimonHausdorf** [aserafin/grape_logging#66]
I am on Rails 6. Version 1.8.2 and 1.8.3 and throwing following error:

    `block in load_missing_constant': uninitialized constant ActiveSupport::ParameterFilter (NameError)

however 1.8.1 is working. Disabling the gem makes the app work again:

```
Loading development environment (Rails 6.0.0)
irb(main):001:0> ActiveSupport::ParameterFilter
=> ActiveSupport::ParameterFilter
```

**Comment by exosty** [comment]
adding explicit ```require 'active_support/parameter_filter'``` in application.rb solved my problem. It seems like gem was loading earlier than active_support/parameter_filter during initialization process somehow

**Comment by SimonHausdorf** [comment]
can confirm that this solved my issue. I will keep it anyway open.

**Comment by davidbasalla** [comment]
When I add `require 'active_support/parameter_filter'` to my application.rb, I see the following error 🤔 

```
FrozenError:
  can't modify frozen #<Class:#<Array:0x000055fd16c339d0>>: ["/app/app/api", "/app/app/channels", "/app/app/controllers", "/app/app/controllers/concerns", "/app/app/jobs", "/app/app/mailers", "/app/app/models", "/app/app/models/concerns", "/app/app/modules"]
```

<details>
  <summary>Full trace</summary>
  
```
FrozenError:
  can't modify frozen #<Class:#<Array:0x000055fd16c339d0>>: ["/app/app/api", "/app/app/channels", "/app/app/controllers", "/app/app/controllers/concerns", "/app/app/jobs", "/app/app/mailers", "/app/app/models", "/app/app/models/concerns", "/app/app/modules"]
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/change_observer.rb:21:in `unshift'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/change_observer.rb:21:in `unshift'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/engine.rb:576:in `block in <class:Engine>'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `instance_exec'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `run'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `each'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `each'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `each'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `each'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `each'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `each'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/initializable.rb:60:in `run_initializers'
# /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/application.rb:363:in `initialize!'
# ./config/environment.rb:7:in `<main>'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
# /usr/local/bundle/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
# ./spec/rails_helper.rb:6:in `<main>'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
# /usr/local/bundle/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
# ./spec/modules/company_spec.rb:3:in `<main>'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
# /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
```
</details>

I'm on:
- Rails (6.0.3.2)
- Grape_logging (1.8.3)

**Comment by flanger001** [comment]
I am also getting this on a brand new Ruby 2.7.0  & Rails 6.0.3.2 application. Here is my Gemfile:

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby `cat .ruby-version`.chomp # 2.7.0

gem "bcrypt"
gem "bootsnap", require: false
gem "pg"
gem "puma"
gem "rack-cors"
gem "rails"
gem "rubocop"

# Grape
gem "grape"
gem "grape-entity"
gem "grape_logging"
gem "grape-swagger"
gem "grape-swagger-entity"

group :development, :test do
  gem "rspec-rails"
  gem "pry-rails"
end

group :test do
  gem "webmock"
end

group :development do
  gem "listen"
end
```

Here is the full stack trace:

```
18: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<top (required)>'
17: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
16: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
15: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
14: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
13: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
12: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
11: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
10: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:141:in `block in perform'
9: from /Users/davidshaffer/Dropbox/Coding/Personal/Apps/cover_band/cover_band_api/config/application.rb:20:in `<top (required)>'
8: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler.rb:174:in `require'
7: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
6: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
5: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
4: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
3: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
2: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
1: from /Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/grape_logging-1.8.3/lib/grape_logging.rb:17:in `<top (required)>'
/Users/davidshaffer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/grape_logging-1.8.3/lib/grape_logging/util/parameter_filter.rb:9:in `<top (required)>': uninitialized constant ActiveSupport::ParameterFilter (NameError)
```

Adding `require "active_support/parameter_filter"` to the top of `application.rb` does fix this, however this seems subpar. This is weird because I have some applications that have this same setup, though I would be willing to bet the reason those apps work and this one doesn't is because they load all of `ActiveSupport` by the time this gem is loaded.

**Comment by aserafin** [comment]
fixed with https://github.com/aserafin/grape_logging/pull/72 thanks again @flanger001 💪
